import type { Metadata } from "next";
import "./globals.css";
import React from "react";


export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by Oleh next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
          {/*<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet"/>*/}
          <title>QQ</title>
      </head>

      <body data-themes="luxury">
      {children}
      </body>
      </html>
  );
}
